spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23limYcRxmgFbr2osk
            client-secret: 309748d1c565d5043d6ab7a078c878864bdfaf6e
            scope: read:user, user:email
            redirect-uri: "http://localhost:8080/login/oauth2/code/github"
            client-name: GitHub
